import Head from 'next/head';
import Category from '../../components/category/Category';
import ContactPart from '../../components/ContactPart';

const CategoryPage = () => {
  return (
    <div>
      <Head>
        <title>دسته بندی</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <h4 className='text-white text-8xl text-center pt-32 h-[40vh] bg-[#111111]'>
        دسته بندی
      </h4>
      <div className='grid grid-cols-1 md:grid-cols-2 gap-x-[20px] pt-28 pb-96 justify-center w-full h-full bg-black px-32'>
        <Category
          img='http://be.beantownthemes.com/html/content/carparts/images/carparts-category-pic3-480x307.jpg'
          category='دسته'
        />
        <Category
          img='http://be.beantownthemes.com/html/content/carparts/images/carparts-category-pic5-480x307.jpg'
          category='دسته'
        />
        <Category
          img='http://be.beantownthemes.com/html/content/carparts/images/carparts-category-pic6-480x307.jpg'
          category='دسته'
        />
        <Category
          img='http://be.beantownthemes.com/html/content/carparts/images/carparts-category-pic1-480x307.jpg'
          category='دسته'
        />
        <Category
          img='http://be.beantownthemes.com/html/content/carparts/images/carparts-category-pic4-480x307.jpg'
          category='دسته'
        />
        <Category
          img='http://be.beantownthemes.com/html/content/carparts/images/carparts-category-pic7-480x307.jpg'
          category='دسته'
        />
      </div>
      <ContactPart />
    </div>
  );
};

export default CategoryPage;
