import Paginator from '../../components/Paginator';
import Product from '../../components/Product';
import Head from 'next/head';
import Resource from '../../public/Resource';

const ProductsPage = () => {
  return (
    <div>
      <Head>
        <title>محصولات</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <h4 className='text-white text-8xl mb-16 text-center pt-32 h-[40vh] bg-[#111111]'>
        محصولات
      </h4>
      <div className='w-full h-full bg-white py-10 px-24 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-x-[10px] gap-y-[40px]'>
        <Product
          img={Resource.Images.IMAGE_1}
          name='تایر'
          price='5000'
          code='Mg-786124'
          manufecturer='شرکت دیجی کالا'
          page='Products'
        />
        <Product
          img={Resource.Images.IMAGE_2}
          name='تایر'
          price='5000'
          code='Mg-786124'
          manufecturer='شرکت دیجی کالا'
          page='Products'
        />
        <Product
          img={Resource.Images.IMAGE_3}
          name='تایر'
          price='5000'
          code='Mg-786124'
          manufecturer='شرکت دیجی کالا'
          page='Products'
        />
        <Product
          img={Resource.Images.IMAGE_4}
          name='تایر'
          price='5000'
          code='Mg-786124'
          manufecturer='شرکت دیجی کالا'
          page='Products'
        />
        <Product
          img={Resource.Images.IMAGE_5}
          name='تایر'
          price='5000'
          code='Mg-786124'
          manufecturer='شرکت دیجی کالا'
          page='Products'
        />
        <Product
          img={Resource.Images.IMAGE_6}
          name='تایر'
          price='5000'
          code='Mg-786124'
          manufecturer='شرکت دیجی کالا'
          page='Products'
        />
        <Product
          img={Resource.Images.IMAGE_7}
          name='تایر'
          price='5000'
          code='Mg-786124'
          manufecturer='شرکت دیجی کالا'
          page='Products'
        />
        <Product
          img={Resource.Images.IMAGE_8}
          name='تایر'
          price='5000'
          code='Mg-786124'
          manufecturer='شرکت دیجی کالا'
          page='Products'
        />
        <Product
          img={Resource.Images.IMAGE_9}
          name='تایر'
          price='5000'
          code='Mg-786124'
          manufecturer='شرکت دیجی کالا'
          page='Products'
        />
        <Product
          img={Resource.Images.IMAGE_10}
          name='تایر'
          price='5000'
          code='Mg-786124'
          manufecturer='شرکت دیجی کالا'
          page='Products'
        />
        <Product
          img={Resource.Images.IMAGE_11}
          name='تایر'
          price='5000'
          code='Mg-786124'
          manufecturer='شرکت دیجی کالا'
          page='Products'
        />
        <Product
          img={Resource.Images.IMAGE_12}
          name='تایر'
          price='5000'
          code='Mg-786124'
          manufecturer='شرکت دیجی کالا'
          page='Products'
        />
      </div>
      <Paginator />
    </div>
  );
};

export default ProductsPage;
