import Head from 'next/head';
import ContactPart from '../components/ContactPart';
import Hero from '../components/index/Hero';
import Product from '../components/Product';
import Service from '../components/index/Service';
import SideImg from '../components/SideImg';
import { useRouter } from 'next/router';
import Resource from '../public/Resource';

export default function HomePage() {
  const router = useRouter();
  return (
    <main className='w-full flex flex-col justify-center items-center bg-[url("http://be.beantownthemes.com/html/content/carparts/images/carparts-sectionbg2.png") bg-center bg-no-repeat bg-cover]'>
      <Head>
        <title>خانه</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Hero />
      <div className='grid grid-cols-1 sm:grid sm:grid-cols-2 md:grid md:grid-cols-3 lg:flex lg:justify-center lg:items-center mt-64 mb-24'>
        <Service
          img={Resource.Images.GUARANTEE_IMG}
          title='گارانتی بازگشت در 30 روز'
          description='ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده
        از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون'
        />
        <Service
          img={Resource.Images.FREE_IMG}
          title='ارسال رایگان'
          description='ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده
        از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون'
        />
        <Service
          img={Resource.Images.FAST_IMG}
          title='تحویل سریع'
          description='ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده
        از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون'
        />
        <Service
          img={Resource.Images.SAFE_IMG}
          title='تحویل سالم'
          description='ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده
        از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون'
        />
      </div>
      <div className='flex flex-col justify-center items-center px-28 py-32 w-full bg-[#111111]'>
        <div className='flex md:flex-row flex-col justify-between w-full items-center mb-20'>
          <h4 className='text-white text-4xl text-center md:text-6xl mb-12 md:mb-0'>
            محصولات اخیر
          </h4>
          <button
            onClick={() => router.push(Resource.Routes.PRODUCTS)}
            className='relative overflow-hidden z-10 transition-all duration-500 ease-in-out text-white rounded-full py-8 md:px-24 text-2xl
          after:content-[""] after:absolute after:bottom-[0] after:left-[0] after:w-full after:h-full px-16
          after:bg-[#262626] after:rounded-full after:-z-20 before:content-[""] before:absolute before:bottom-[0] before:left-[0] before:w-[0%] before:h-full
          before:bg-[#222222] before:rounded-full before:-z-10 before:transition-all before:duration-500 hover:before:w-full'
          >
            مشاهده تمام محصولات
          </button>
        </div>
        <div className='grid grid-cols-1 sm:grid sm:grid-cols-2 md:grid md:grid-cols-3 lg:flex lg:items-center lg:justify-center w-full h-full'>
          <Product
            img={Resource.Images.IMAGE_1}
            name='تایر'
            price='5000'
            code='Mg-786124'
            manufecturer='شرکت دیجی کالا'
          />
          <Product
            img={Resource.Images.IMAGE_4}
            name='تایر'
            price='5000'
            code='Mg-786124'
            manufecturer='شرکت دیجی کالا'
          />
          <Product
            img={Resource.Images.IMAGE_2}
            name='تایر'
            price='5000'
            code='Mg-786124'
            manufecturer='شرکت دیجی کالا'
          />
          <Product
            img={Resource.Images.IMAGE_3}
            name='تایر'
            price='5000'
            code='Mg-786124'
            manufecturer='شرکت دیجی کالا'
          />
        </div>
      </div>
      <div className='flex flex-col justify-center items-center px-24 py-32 w-full bg-black'>
        <div className='flex flex-col md:flex-row justify-between w-full items-center mb-20'>
          <h4 className='text-white mb-12 md:mb-0 text-4xl text-center md:text-6xl'>
            محصولات دارای تخفیف
          </h4>
          <button
            onClick={() => router.push(Resource.Routes.PRODUCTS)}
            className='relative overflow-hidden z-10 transition-all duration-500 ease-in-out text-white rounded-full py-8 md:px-24 text-2xl
          after:content-[""] after:absolute after:bottom-[0] after:left-[0] after:w-full after:h-full px-16
          after:bg-[#262626] after:rounded-full after:-z-20 before:content-[""] before:absolute before:bottom-[0] before:left-[0] before:w-[0%] before:h-full
          before:bg-[#222222] before:rounded-full before:-z-10 before:transition-all before:duration-500 hover:before:w-full'
          >
            مشاهده تمام محصولات
          </button>
        </div>
        <div className='grid grid-cols-1 sm:grid sm:grid-cols-2 md:grid md:grid-cols-3 lg:flex lg:items-center lg:justify-center w-full h-full'>
          <Product
            img={Resource.Images.IMAGE_5}
            name='تایر'
            price='5000'
            code='Mg-786124'
            manufecturer='شرکت دیجی کالا'
          />
          <Product
            img={Resource.Images.IMAGE_6}
            name='تایر'
            price='5000'
            code='Mg-786124'
            manufecturer='شرکت دیجی کالا'
          />
          <Product
            img={Resource.Images.IMAGE_7}
            name='تایر'
            price='5000'
            code='Mg-786124'
            manufecturer='شرکت دیجی کالا'
          />
          <Product
            img={Resource.Images.IMAGE_8}
            name='تایر'
            price='5000'
            code='Mg-786124'
            manufecturer='شرکت دیجی کالا'
          />
        </div>
      </div>
      <SideImg />
      <ContactPart />
    </main>
  );
}
